- name: Set up Node
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Install frontend dependencies
  working-directory: frontend
  run: npm install --legacy-peer-deps

- name: Build frontend
  working-directory: frontend
  run: npm run build
