runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

manual_scaling:
  instances: 1

network:
  session_affinity: true

resources:
  cpu: 4
  memory_gb: 4

entrypoint: yarn start:prod
