runtime: nodejs22
env: flex
service: frontend

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180

entrypoint: npm start

env_variables:
  NODE_ENV: production
