runtime: nodejs     # or nodejs14 if 16 isn’t supported in your region
env: standard
instance_class: F1

handlers:
  # Serve built files at their matching paths
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  # Fallback for client-side routing
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
