runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 180

resources:
  cpu: 1
  memory_gb: 2

env_variables:
  GOOGLE_API_KEY: "AIzaSyBzogMhONMlInEHBLOQb33y7AY1gvEi_3Y"    

handlers:
  - url: /.*
    script: this field is required, but ignored
