service: backend
runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 180

resources:
  cpu: 1
  memory_gb: 2

env_variables:
  GOOGLE_API_KEY: "AIzaSyBzogMhONMlInEHBLOQb33y7AY1gvEi_3Y"
  MISTRAL_API_KEY: "IK1Mulp1ebx52dtXOpcFrxZjwtEIpNJN"
  CLOUDFLARE_API_TOKEN: "JCYaQZwuhPpLy3sXxi8qOYtRS6JCXzbR1GMo33Ni"
  CLOUDFLARE_ACCOUNT_ID: "85da2e9c112a69206d0930ac6aeeeaef"
  STABLE_HORDE_KEY: "_TSt6gmY0Q0VmhkJG8UNhA"
  HUGGINGFACE_API_KEY: "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"

entrypoint: java -Dserver.port=$PORT -jar target/llm-comparison-backend-1.0.0.jar

handlers:
  - url: /.*
    script: this field is required, but ignored
