runtime: java
env: flex
service: backend

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180

handlers:
  - url: /.*
    script: this field is required, but ignored
