runtime: java17
env: flex
service: backend

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180

handlers:
  - url: /.*
    script: this field is required, but ignored
