runtime: java
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"

automatic_scaling:
  min_num_instances: 0  
  max_num_instances: 2  

resources:
  cpu: 1         
  memory_gb: 2   

handlers:
  - url: /.*
    script: this field is required, but ignored
