name: Deploy to Google App Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: llm-comparison-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1) Build Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn & build frontend
        working-directory: frontend
        run: |
          npm install -g yarn
          yarn install --ignore-engines
          yarn build

      # 2) Authenticate & configure gcloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>=420.0.0'

      - name: Ensure App Engine exists
        run: |
          if ! gcloud app describe --project="$PROJECT_ID" > /dev/null 2>&1; then
            gcloud app create --project="$PROJECT_ID" --region="us-central"
          fi

      # 3) Deploy Frontend (static)
      - name: Deploy frontend to App Engine
        working-directory: frontend
        run: |
          gcloud app deploy app.yaml \
            --project="$PROJECT_ID" \
            --quiet \
            --stop-previous-version

      # 4) Build & deploy Backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Deploy backend to App Engine
        working-directory: backend
        run: |
          gcloud app deploy app.yaml \
            --project="$PROJECT_ID" \
            --quiet \
            --stop-previous-version
